apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: personal-website
  template:
    metadata:
      labels:
        app: personal-website
    spec:
      containers:
      - name: personal-website
        image: personal-website:latest
        ports:
        - containerPort: 8080
    